set termguicolors
syntax on
set background=dark
colorscheme gruvbox

filetype plugin indent on
set autoindent
set cursorline
set colorcolumn=125
set encoding=utf-8
set expandtab
set fileformat=unix
set hidden
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set mouse=a
set nobackup
set nocompatible
set noswapfile
set number
set relativenumber
set ruler
set shiftwidth=5
set showcmd
set showmode
set smartcase
set smarttab
set softtabstop=5
set splitbelow
set splitright
set tabstop=5
set signcolumn=yes

let mapleader = " "
nnoremap <leader>e :Ex<CR>

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

nnoremap <leader>h :nohlsearch<CR>

nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>

nnoremap <leader>bn :bnext<CR>
nnoremap <leader>bp :bprevious<CR>
nnoremap <leader>bd :bdelete<CR>

nnoremap <leader>g :Git<CR>
nnoremap <leader>t :TagbarToggle<CR>

nnoremap <D-k> :m .-2<CR>==
nnoremap <D-j> :m .+1<CR>==

" nnoremap <D-h> :vertical resize -2<CR>
" nnoremap <D-l> :vertical resize +2<CR>
" nnoremap <D-j> :resize -2<CR>
" nnoremap <D-k> :resize +2<CR>

set tags=./tags;/

let g:netrw_dirhistmax = 0
let g:netrw_sort_by = "name"
let g:netrw_sort_direction = "normal"
let g:netrw_liststyle = 1

nnoremap <D-1> 1gt
nnoremap <D-2> 2gt
nnoremap <D-3> 3gt
nnoremap <D-4> 4gt
nnoremap <D-5> 5gt
nnoremap <D-6> 6gt
nnoremap <D-7> 7gt
nnoremap <D-8> 8gt
nnoremap <D-9> 9gt
