set termguicolors
syntax on
colorscheme gruvbox
set background=dark

filetype plugin indent on
set autoindent
set cursorline
set colorcolumn=125
set encoding=utf-8
set expandtab
set fileformat=unix
set hidden
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set mouse=a
set nobackup
set nocompatible
set noswapfile
set number
set relativenumber
set ruler
set shiftwidth=5
set showcmd
set showmode
set smartcase
set smarttab
set softtabstop=5
set splitbelow
set splitright
set tabstop=5
set signcolumn=yes

let mapleader = " "
nnoremap <leader>e :Ex<CR>

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

nnoremap <leader>h :nohlsearch<CR>

nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>

nnoremap <leader>bn :bnext<CR>
nnoremap <leader>bp :bprevious<CR>
nnoremap <leader>bd :bdelete<CR>

nnoremap <leader>G :Git<CR>

nnoremap <D-k> :m .-2<CR>==
nnoremap <D-j> :m .+1<CR>==

" nnoremap <D-h> :vertical resize -2<CR>
" nnoremap <D-l> :vertical resize +2<CR>
" nnoremap <D-j> :resize -2<CR>
" nnoremap <D-k> :resize +2<CR>
